### PR TITLE
Reflect python indention is now ok 

### PR DESCRIPTION
**Pull request by dflvunoooooo**
I thought it would be nice, if the manual would reflect the fact, that python code can now be indented. I added four spaces bevor every python line and removed the warning under 5.13.1 Python code and instead copied the note to use version 2.6 or higher. 

I am wondering if two or four spaces should be used. Everywhere two are used, but in python code, there are four used.

I hope PRs are welcome.

### CODE REVIEW

**Comment by tobiasBora** [comment]
Thanks a lot for the PR.

The main reason I didn't want to indent the code in the example is that people might read this documentation while using an older version of the lib, and they might be disturbed by the non-predictable result/possible error. But you are right, it would be nice to say a word on the fact that code may be indented maybe earlier. Right now I say it in a comment `# See, you can indent this code with two spaces without disturbing python (that expects no indentation)`, but it is quite late in the documentation, and right now the documentation contains contradictions like `Importantly: you do not want to indent the content of CacheMeCode, or the space will also appear in the final code.` ^^'. Not sure what is the best option here, maybe a comment at the beginning of the first python code like `# if you use v2.7 or above, you can freely indent this code` while keeping the code not indented…

**Comment by tobiasBora** [comment]
Or otherwise, we can maybe keep your changes, but add on the very first occurrence of a python code a warning in a comment containing your note. Note that I would rather specify v2.7 instead of v2.6 as 2.7 also allows indentation in `placeholderFromCode`.

**Comment by dflvunoooooo** [comment]
Yes, I assumed something like that. I think backwards compatibility is important, but the manual should reflect the current state, should it not? I would say a note at the beginning of the python sub chapter and at the first python example should be sufficient?  

Then there remains the question how many spaces as indention you like best, two or four?

**Comment by dflvunoooooo** [comment]
By the way, is there an option for the package to specify which version should be used?

**Comment by dflvunoooooo** [comment]
I added the note "Note that if you use a version before 2.7, you cannot indent the python code" at the first two mentions of python before the python chapter and at the beginning of the python chapter I added "Note that if you use a version before 2.7, you cannot indent the python code (i.e. the first line must not start with any space)".

**Comment by tobiasBora** [comment]
Thanks!

> the manual should reflect the current state, should it not?

Well, I guess yes, but given how distributions tend to distribute outdated texlive installation, I was afraid to see users quickly copy/paste code from a more recent documentation that would not compile locally.

**Comment by dflvunoooooo** [comment]
I see, that can lead to problems. Should we add a note inside the first three python code environments too?

**Pull request merged**
